feat: AB#69 Handle Preview image of apptemplate
witchpou/lj-projectbuilder pull request #291
Opened 2022-04-05 12:31 UTC by DerCed

## Description
Added apptemplate image preview

## Motivation and Context
Added image to better differentiate between apptemplates

## How has this been tested?
Added string image file to demo template
Checked regex in regex 101
A wrong specified image results in ``Template configuration could not be loaded. Please check config file (template-config.json).``

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/16734873/161753865-62b2f693-47ef-45d3-93ac-efaa2b9387b2.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-04-05 12:35 UTC, DerCed commented on persistence/src/main/java/de/starwit/persistence/entity/AppTemplate.java
> +	private String imageUrl;
Änderung hier

2022-04-05 12:35 UTC, DerCed commented on service/src/main/java/de/starwit/dto/SaveAppTemplateDto.java
> +    private String imageUrl;
Änderung hier

2022-04-05 12:35 UTC, DerCed commented on service/src/main/java/de/starwit/mapper/AppTemplateMapper.java
> +        dto.setImageUrl(entity.getImageUrl());
Änderung hier

2022-04-05 12:35 UTC, DerCed commented on service/src/main/java/de/starwit/mapper/AppTemplateMapper.java
> +        entity.setImageUrl(dto.getImageUrl());
Änderung hier

2022-04-06 07:09 UTC, witchpou requested changes
undo formatting

2022-04-06 07:09 UTC, witchpou commented on service/src/main/java/de/starwit/mapper/AppTemplateMapper.java
> -package de.starwit.mapper;
rejected because of formatting

2022-04-06 07:14 UTC, witchpou commented on service/src/main/java/de/starwit/mapper/AppTemplateMapper.java
> -package de.starwit.mapper;
line endings changed to CRLF
![image](https://user-images.githubusercontent.com/10485792/161916960-02e764fa-752e-4d3b-ab1e-a41658288bf6.png)

2022-04-06 13:13 UTC, merged